---
title: "pagedtable POC"
output:
  html_document
editor_options:
  chunk_output_type: inline
---

```{r, message = FALSE}

library(dplyr)
library(colortable)

## remotes::install_github("thebioengineer/pagedtable")
library(pagedtable)

```


```{r}
#default widget
pagedtable(x = mtcars)

# set nrows displayed to 7
pagedtable(x = mtcars, pagerows_min = 7)

```


```{r}

# add a special vector, based on vctrs that returns HTML
mtcars2 <- mtcars
mtcars2$mpg <- color_vctr(mtcars2$mpg, text_color = color_scale("Blues"))

# problem is, it didnt realize it needed to treat my field like it was html!
pagedtable(mtcars2, pagerows = 10)
```

```{r}

## create a pagedtable_col method for your class, and set the html setting for the 
## column to be TRUE, voila! On rendering of the column it will to render 
## the html!

pagedtable_col.color_vctr <- function(x, name = substitute(x), ...) {
  col_values <- format(x, ..., method = "html")

  baseType <- class(vctrs::field(x,"vctr"))[[1]]
  type <- type_sum(x)

  list(
    content = col_values,
    columns = list(
      name  = name,
      label = name,
      type  = vctrs::vec_ptype_abbr(x),
      align = "left",
      html = TRUE
    )
  )
}

pagedtable(mtcars2, pagerows_min = 10)

```
