---
title: "pagedtable Example!"
output:
  html_document
editor_options:
  chunk_output_type: console
---

```{r setup}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE,message = FALSE)
```

```{r}
library(dplyr)
library(colortable)
library(pagedtable)

z <- pagedtable(mtcars)
z
```


```{r}
mtcars2 <- mtcars
mtcars2$mpg <- color_vctr(mtcars2$mpg, text_color = color_scale("Blues"))
pagedtable(mtcars2, pagerows = 10)

```

```{r}

## create new method for your class

pagedtable_col.color_vctr <- function(x, name = substitute(x), ...) {
  col_values <- format(x, ..., method = "html")

  baseType <- class(vctrs::field(x,"vctr"))[[1]]
  type <- type_sum(x)

  list(
    content = col_values,
    columns = c(
      name  = name,
      label = name,
      type  = vctrs::vec_ptype_abbr(x),
      align = "left",
      html = TRUE
    )
  )
}

pagedtable(mtcars2, pagerows = 10)



```
```{r}

library(dplyr)
library(colortable)
library(pagedtable)

mtcars_grouped <- mtcars %>% 
  group_by(cyl) %>% 
  summarise(
    cars = list(data.frame(
      cars = .data$cars,
      mpg = .data$mpg,
      disp = .data$disp
    )),
    mean_mpg = mean(mpg),
    mean_disp = mean(disp)
  )

pagedtable(mtcars_grouped, use_rownames = FALSE)

```

